/*
 * This Scala source file was generated by the Gradle 'init' task.
 */
package dev.shaga.jackit.lambda

import dev.shaga.jackit.lambda.process.ProcessInput

object App {
  def main(args: Array[String]): Unit = {
    val input = "" // Put input here to run and test locally
    ProcessInput.processJson(input)

  }

}
